/**
 * generate-tokens.js
 *
 * Reads color-tokens.json and design-tokens.tokens.json, then outputs
 * a single tokens.css file containing every design token as a CSS
 * custom property under :root.
 *
 * Usage:  node generate-tokens.js
 *
 * Color system strategy:
 *   • Primitive palette values  → --color-palette-{group}-{stop}
 *   • Key colors                → --color-key-{name}
 *   • Semantic role colors      → --color-{role}   (light theme in :root,
 *                                                    dark theme in [data-theme="dark"])
 *   • Role variables reference primitives via var() so the UI only ever
 *     touches --color-* role tokens, never the primitives directly.
 *
 * Typography strategy:
 *   • Each type style (e.g. "display large") produces variables for
 *     font-family, font-size, font-weight, line-height, letter-spacing.
 */

const fs   = require('fs');
const path = require('path');

// ── File paths ──────────────────────────────────────────────────────
const COLOR_JSON = path.join(__dirname, 'color-tokens.json');
const TYPO_JSON  = path.join(__dirname, 'design-tokens.tokens.json');
const OUTPUT_CSS = path.join(__dirname, 'tokens.css');

// ── Helpers ─────────────────────────────────────────────────────────

/**
 * Convert a camelCase or PascalCase string to kebab-case.
 * "onPrimaryContainer" → "on-primary-container"
 * "neutralVariant"     → "neutral-variant"
 */
function toKebab(str) {
  return str
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

/**
 * Convert a token style name like "display large" or "label small ii"
 * to a kebab-case CSS-variable suffix: "display-large", "label-small-ii".
 */
function styleNameToKebab(name) {
  return name.trim().toLowerCase().replace(/\s+/g, '-');
}

/**
 * Resolve a token reference like "{color.palette.primary.80}" into the
 * corresponding CSS var() call, e.g. var(--color-palette-primary-80).
 * Also handles "{color.key.primary}".
 */
function resolveRef(ref) {
  // Strip the braces
  const inner = ref.replace(/^\{/, '').replace(/\}$/, '');
  const parts = inner.split('.');

  // color.palette.<group>.<stop>
  if (parts[0] === 'color' && parts[1] === 'palette') {
    const group = toKebab(parts[2]);
    const stop  = parts[3];
    return `var(--color-palette-${group}-${stop})`;
  }

  // color.key.<name>
  if (parts[0] === 'color' && parts[1] === 'key') {
    const name = toKebab(parts[2]);
    return `var(--color-key-${name})`;
  }

  // Fallback — shouldn't happen but keeps things safe
  return ref;
}

/**
 * Add proper CSS units to a numeric typography value.
 */
function addUnit(prop, value) {
  if (typeof value !== 'number') return value;
  if (prop === 'fontWeight') return value;           // unitless
  if (prop === 'fontSize' || prop === 'lineHeight' || prop === 'letterSpacing') {
    return `${value}px`;
  }
  return value;
}

// ── Read JSON sources ───────────────────────────────────────────────
const colorData = JSON.parse(fs.readFileSync(COLOR_JSON, 'utf-8'));
const typoData  = JSON.parse(fs.readFileSync(TYPO_JSON,  'utf-8'));

// ── Build CSS lines ─────────────────────────────────────────────────
const lines = [];

lines.push('/*');
lines.push(' * tokens.css — auto-generated by generate-tokens.js');
lines.push(' * Single source of truth for all design tokens.');
lines.push(' *');
lines.push(' * COLOR USAGE RULES:');
lines.push(' *   ✅  Use semantic role variables:  var(--color-primary)');
lines.push(' *   ❌  Never reference primitives directly:  var(--color-palette-primary-40)');
lines.push(' *');
lines.push(` * Generated: ${new Date().toISOString()}`);
lines.push(' */');
lines.push('');

// ── 1. :root — primitives + light-mode roles + typography ───────────

lines.push(':root {');

// ── 1a. Key colors (reference palette) ──────────────────────────────
lines.push('');
lines.push('  /* ═══════════════════════════════════════════');
lines.push('     Key Colors (source hues)');
lines.push('     ═══════════════════════════════════════════ */');

const keys = colorData.color.key;
for (const [name, value] of Object.entries(keys)) {
  lines.push(`  --color-key-${toKebab(name)}: ${value};`);
}

// ── 1b. Palette primitives ──────────────────────────────────────────
lines.push('');
lines.push('  /* ═══════════════════════════════════════════');
lines.push('     Palette Primitives');
lines.push('     ⚠  Do NOT reference these in application CSS.');
lines.push('     They exist only so semantic roles can be built from them.');
lines.push('     ═══════════════════════════════════════════ */');

const palette = colorData.color.palette;
for (const [group, stops] of Object.entries(palette)) {
  lines.push('');
  lines.push(`  /* ${group} */`);
  for (const [stop, value] of Object.entries(stops)) {
    lines.push(`  --color-palette-${toKebab(group)}-${stop}: ${value};`);
  }
}

// ── 1c. Semantic color roles (light theme = default) ────────────────
lines.push('');
lines.push('  /* ═══════════════════════════════════════════');
lines.push('     Semantic Color Roles — Light Theme (default)');
lines.push('     ✅  Use these in your application styles.');
lines.push('     ═══════════════════════════════════════════ */');

const lightRoles = colorData.color.role.light;
for (const [role, ref] of Object.entries(lightRoles)) {
  const resolved = resolveRef(ref);
  lines.push(`  --color-${toKebab(role)}: ${resolved};`);
}

// ── 1d. Typography tokens ───────────────────────────────────────────
lines.push('');
lines.push('  /* ═══════════════════════════════════════════');
lines.push('     Typography Tokens');
lines.push('     ═══════════════════════════════════════════ */');

// Use the "typography" section (structured with type/value pairs)
const typography = typoData.typography;
const typographyProps = ['fontFamily', 'fontSize', 'fontWeight', 'lineHeight', 'letterSpacing'];
const cssPropSuffix = {
  fontFamily:     'font-family',
  fontSize:       'font-size',
  fontWeight:     'font-weight',
  lineHeight:     'line-height',
  letterSpacing:  'letter-spacing',
};

for (const [styleName, props] of Object.entries(typography)) {
  const slug = styleNameToKebab(styleName);
  lines.push('');
  lines.push(`  /* ${styleName} */`);
  for (const prop of typographyProps) {
    if (props[prop]) {
      const rawValue = props[prop].value ?? props[prop];
      const value    = addUnit(prop, rawValue);
      const suffix   = cssPropSuffix[prop];
      // Wrap font-family in quotes for safety
      const formatted = prop === 'fontFamily' ? `"${value}"` : value;
      lines.push(`  --font-${slug}-${suffix}: ${formatted};`);
    }
  }
}

lines.push('}');

// ── 2. Dark theme override ──────────────────────────────────────────
lines.push('');
lines.push('/* ═══════════════════════════════════════════');
lines.push('   Semantic Color Roles — Dark Theme');
lines.push('   Activate by adding data-theme="dark" to <html> or <body>.');
lines.push('   ═══════════════════════════════════════════ */');
lines.push('');
lines.push('[data-theme="dark"] {');

const darkRoles = colorData.color.role.dark;
for (const [role, ref] of Object.entries(darkRoles)) {
  const resolved = resolveRef(ref);
  lines.push(`  --color-${toKebab(role)}: ${resolved};`);
}

lines.push('}');
lines.push('');

// ── Write output ────────────────────────────────────────────────────
fs.writeFileSync(OUTPUT_CSS, lines.join('\n'), 'utf-8');
console.log(`✅  tokens.css generated → ${OUTPUT_CSS}`);
console.log(`    • ${Object.keys(keys).length} key colors`);
console.log(`    • ${Object.values(palette).reduce((n, s) => n + Object.keys(s).length, 0)} palette primitives`);
console.log(`    • ${Object.keys(lightRoles).length} light-mode role tokens`);
console.log(`    • ${Object.keys(darkRoles).length} dark-mode role tokens`);
console.log(`    • ${Object.keys(typography).length} typography styles (× 5 properties each)`);
